AutoLot/AutoLot.Mvc/Models/ErrorViewModel.cs
using System;

namespace AutoLot.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AutoLot/AutoLot.Mvc/Controllers/CarsController.cs
using System;
using System.Threading.Tasks;
using AutoLot.Dal.Models.Entities;
using AutoLot.Mvc.ServiceInfo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AutoLot.Mvc.Controllers
{
    [Route("[controller]/[action]")]
    public class CarsController : Controller
    {
        private readonly IAutoLotServiceWrapper _serviceWrapper;

        public CarsController(IAutoLotServiceWrapper serviceWrapper)
        {
            _serviceWrapper = serviceWrapper;
        }

        // GET: Cars
        [HttpGet]
        [Route("/[controller]")]
        [Route("/[controller]/[action]")]
        public async Task<IActionResult> Index() => View(await _serviceWrapper.GetAllAsync<Car>());

        [HttpGet("{makeId}/{makeName}")]
        [Route("/[controller]/[action]")]
        public async Task<IActionResult> ByMake(int makeId, string makeName)
        {
            ViewBag.MakeName = makeName;
            return View(await _serviceWrapper.GetCarsByMakeAsync(makeId));
        }

        // GET: Cars/Details/5
        [HttpGet("{id?}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _serviceWrapper.GetOneAsync<Car>(id.Value);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        internal async Task<SelectList> GetMakes()
            => new SelectList(await _serviceWrapper.GetAllAsync<Make>(), nameof(Make.Id), nameof(Make.Name));

        // GET: Cars/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewData["MakeId"] = await GetMakes();
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //public async Task<IActionResult> Create([Bind("MakeId,Color,PetName,Id,TimeStamp")] Car car)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car car)
        {
            if (ModelState.IsValid)
            {
                var newCar = await _serviceWrapper.AddOneAsync(car);
                return RedirectToAction(nameof(Details), new { id = newCar.Id });
            }

            ViewData["MakeId"] = await GetMakes();
            return View(car);
        }

        // GET: Cars/Edit/5
        [HttpGet("{id?}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _serviceWrapper.GetOneAsync<Car>(id.Value);
            if (car == null)
            {
                return NotFound();
            }

            ViewData["MakeId"] = await GetMakes();
            return View(car);
        }

        // POST: Cars/Edit/5
        [HttpPost("{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Car car)
        {
            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _serviceWrapper.UpdateOneAsync(car);
                return RedirectToAction(nameof(Details), new { id = car.Id });
            }

            ViewData["MakeId"] = await GetMakes();
            return View(car);
        }
        //Model Binding: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1

        // GET: Cars/Delete/5
        [HttpGet("{id?}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _serviceWrapper.GetOneAsync<Car>(id.Value);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        //[ActionName("Delete")]
        [HttpPost("{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, byte[] timeStamp)
        {
            await _serviceWrapper.DeleteOneAsync(new Car { Id = id, TimeStamp = timeStamp });
            return RedirectToAction(nameof(Index));
        }
    }
}

AutoLot/AutoLot.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AutoLot.Mvc.Models;
using AutoLot.Dal.Models.Entities;

namespace AutoLot.Mvc.Controllers
{
    [Route("[controller]/[action]")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Route("/")]
        [Route("/[controller]")]
        [Route("/[controller]/[action]")]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> RazorSyntax()
        {
            //var car = await serviceWrapper.GetOneAsync<Car>(1);
            var car = new Car { Id = 1, PetName = "Herbie" };
            return View(car);
        }

        [HttpGet]
        public IActionResult TestDisplayTemplates()
        {
            return View(DateTime.Now);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AutoLot/AutoLot.Mvc/ViewComponents/MenuViewComponent.cs
using System.Threading.Tasks;
using AutoLot.Dal.Models.Entities;
using AutoLot.Mvc.ServiceInfo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace AutoLot.Mvc.ViewComponents
{
    //https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components
    //The runtime searches for the view in the following paths:
    //    Views/<controller_name>/Components/<view_component_name>/<view_name>
    //    Views/Shared/Components/<view_component_name>/<view_name>
    //    /Pages/Shared/Components/<View Component Name>/<View Name>

    public class MenuViewComponent : ViewComponent
    {
        private readonly IAutoLotServiceWrapper _serviceWrapper;

        public MenuViewComponent(IAutoLotServiceWrapper serviceWrapper)
        {
            _serviceWrapper = serviceWrapper;
        }

        //public IViewComponentResult Invoke()
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var makes = await _serviceWrapper.GetAllAsync<Make>();
            if (makes == null)
            {
                return new ContentViewComponentResult("Unable to get the makes");
            }

            return View("MenuView", makes);
        }

    }
}

AutoLot/AutoLot.Mvc/Views/Cars/ByMake.cshtml
@model IEnumerable<Car>

@{
    ViewData["Title"] = "Index";
}

<h1>Vehicle Inventory for @ViewBag.MakeName</h1>

@{
    var mode = new ViewDataDictionary(ViewData) {{"ByMake", true}};
}

<partial name="Partials/_CarListPartial" model="Model" view-data="@mode"/>

AutoLot/AutoLot.Mvc/Views/Cars/Create.cshtml
@model Car

@{
    ViewData["Title"] = "Create";
}

<h1>Create a New Car</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            @Html.EditorForModel()
            <div class="form-group">
                <button type="submit" class="btn btn-success">Create <i class="fas fa-plus"></i></button>&nbsp;&nbsp;|&nbsp;&nbsp;
                <a asp-action="Index" class="text-info">Back to List <i class="fas fa-list"></i></a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoLot/AutoLot.Mvc/Views/Cars/Delete.cshtml
@model Car

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete @Model.PetName</h1>

<h3>Are you sure you want to delete this car?</h3>
<div>
    @Html.DisplayForModel()
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="TimeStamp" />
        <button type="submit" class="btn btn-danger">Delete <i class="fas fa-trash"></i></button>&nbsp;&nbsp;|&nbsp;&nbsp;
        <a asp-action="Index" class="text-info">Back to List <i class="fas fa-list"></i></a>
    </form>
</div>

AutoLot/AutoLot.Mvc/Views/Cars/Details.cshtml
@model Car
@{
    ViewData["Title"] = "Details";
}
<h1>Details for @Model.PetName</h1>
@Html.DisplayForModel()
<div>
    <edit-car car-id="@Model.Id"></edit-car>&nbsp;&nbsp;|&nbsp;&nbsp;
    <delete-car car-id="@Model.Id"></delete-car>&nbsp;&nbsp;|&nbsp;&nbsp;
    <a asp-action="Index" class="text-info">Back to List <i class="fas fa-list"></i></a>
</div>

AutoLot/AutoLot.Mvc/Views/Cars/DisplayTemplates/Car.cshtml
@model Car
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MakeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MakeNavigation.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
    </dl>
</div>

AutoLot/AutoLot.Mvc/Views/Cars/DisplayTemplates/CarWithColors.cshtml
@model AutoLot.Dal.Models.Entities.Car
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MakeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MakeNavigation.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10" style="color:@Model.Color">
            @Html.DisplayFor(model => model.Color)
        </dd>
    </dl>
</div>

AutoLot/AutoLot.Mvc/Views/Cars/Edit.cshtml
@model Car

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit @Model.PetName</h1>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            @Html.EditorForModel()
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="TimeStamp" />
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save <i class="fas fa-save"></i></button>&nbsp;&nbsp;|&nbsp;&nbsp;
                <a asp-action="Index" class="text-info">Back to List <i class="fas fa-list"></i></a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

AutoLot/AutoLot.Mvc/Views/Cars/EditorTemplates/Car.cshtml
@model Car
<div asp-validation-summary="All" class="text-danger"></div>
<div class="form-group">
    <label asp-for="PetName" class="col-form-label"></label>
    <input asp-for="PetName" class="form-control" />
    <span asp-validation-for="PetName" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="MakeNavigation" class="col-form-label"></label>
    <select asp-for="MakeId" class="form-control" asp-items="ViewBag.MakeId"></select>
    <span asp-validation-for="MakeId" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Color" class="col-form-label"></label>
    <input asp-for="Color" class="form-control" />
    <span asp-validation-for="Color" class="text-danger"></span>
</div>

AutoLot/AutoLot.Mvc/Views/Cars/Index.cshtml
@model IEnumerable<Car>

@{
    ViewData["Title"] = "Index";
}

<h1>Vehicle Inventory</h1>

<partial name="Partials/_CarListPartial" model="@Model"/>

AutoLot/AutoLot.Mvc/Views/Cars/Partials/_CarListPartial.cshtml
@model IEnumerable<Car>
@{
    var showMake = true;
    if (bool.TryParse(ViewBag.ByMake?.ToString(), out bool byMake))
    {
        showMake = !byMake;
    }
}
<p>
    <a asp-action="Create" class="text-success">Create New <i class="fas fa-plus"></i></a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PetName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        @if (showMake)
        {
            <th>
                @Html.DisplayNameFor(model => model.MakeNavigation)
            </th>
        }
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            @if (showMake)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.MakeNavigation.Name)
                </td>
            }
            <td>
                <edit-car car-id="@item.Id"></edit-car>&nbsp;&nbsp;|&nbsp;&nbsp;
                <car-details car-id="@item.Id"></car-details>&nbsp;&nbsp;|&nbsp;&nbsp;
                <delete-car car-id="@item.Id"></delete-car>
            </td>
        </tr>
    }
    </tbody>
</table>

AutoLot/AutoLot.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AutoLot/AutoLot.Mvc/Views/Home/RazorSyntax.cshtml
@model AutoLot.Dal.Models.Entities.Car
@{
    ViewData["Title"] = "RazorSyntax";
}

<h1>Razor Syntax</h1>
@for (var i = 0; i < 15; i++)
{
    //do something
}

@{
    //Code Block
    var foo = "Foo";
    var bar = "Bar";
    var htmlString = "<ul><li>one</li><li>two</li></ul>";
}
@foo
<br />
@htmlString
<br />
@foo.@bar
<br />
@foo.ToUpper()
<br/>
@@Html.Raw(htmlString)
<hr />
@{
    @:Straight Text
    <div>Value:@Model.Id</div>
    <text>
        Lines without HTML tag
    </text>
    <br />
}

<hr />
@*
    Multiline Comments
    Hi.
*@
Email Address Handling:
<br />
foo@foo.com
<br />
@@foo
<br />
test@(foo) = testFoo
<br />
<hr />
@functions {
    public static IList<string> SortList(IList<string> strings)
    {
        var list = from s in strings orderby s select s;
        return list.ToList();
    }
}
--------------------------------------------------------------
@{ var myList = new List<string> { "C", "A", "Z", "F" };
    var sortedList = SortList(myList); //MyFunctions.SortList(myList)
}
@foreach (string s in sortedList)
{
    @s@:&nbsp;
}
<hr />
@{
    Func<dynamic, object> b = @<strong>@item</strong>;
}
This will be bold: @b("Foo")

@{ 
    DateTime d1 = DateTime.Now;
    DateTime? d2 = null;
}

AutoLot/AutoLot.Mvc/Views/Home/TestDisplayTemplates.cshtml
@model DateTime
@{
    ViewData["Title"] = "TestDisplayTemplates";
}

<h1>Test Date Time DisplayTemplate</h1>

@Html.DisplayForModel()

AutoLot/AutoLot.Mvc/Views/Shared/Components/Menu/MenuView.cshtml
@model IEnumerable<Make>
<div class="dropdown-menu">
<a class="dropdown-item text-dark" asp-area="" asp-controller="Cars" asp-action="Index">All</a>

@foreach (var item in Model)
{
    <a class="dropdown-item text-dark" asp-controller="Cars" asp-action="ByMake" asp-route-makeId="@item.Id" asp-route-makeName="@item.Name">@item.Name</a>
}
</div>

AutoLot/AutoLot.Mvc/Views/Shared/DisplayTemplates/DateTime.cshtml
@model DateTime?
@if (Model == null)
{
    @:Unknown
}
else
{
    if (ViewData.ModelMetadata.IsNullableValueType)
    {
        @:@(Model.Value.ToString("d"))
    }
    else
    {
        @:@(((DateTime)Model).ToString("d"))
    }
}

AutoLot/AutoLot.Mvc/Views/Shared/Partials/_Head.cshtml
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - AutoLot.Web</title>
    <environment include="Development,Local">
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" asp-append-version="true"/>
    </environment>
    <environment exclude="Development,Local">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>

AutoLot/AutoLot.Mvc/Views/Shared/Partials/_JavaScriptFiles.cshtml
<environment include="Development,Local">
    <script src="~/lib/jquery/jquery.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development,Local">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/jquery.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/js/bootstrap.bundle.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
    </script>
</environment>
<script src="~/js/site.js" asp-append-version="true"></script>

AutoLot/AutoLot.Mvc/Views/Shared/Partials/_Menu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoLot.Mvc</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="RazorSyntax">Razor Syntax <i class="fas fa-cut"></i></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown">Inventory <i class="fa fa-car"></i></a>
                    <vc:menu />
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

AutoLot/AutoLot.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <partial name="Partials/_Head" />
</head>
<body>
    <header>
        <partial name="Partials/_Menu" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AutoLot.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <partial name="Partials/_JavaScriptFiles" />
    @RenderSection("Scripts", required: false)
</body>
</html>